export const LOGIN_ROUTE = "/login"
export const OAUTH_CALLBACK = "/oauth"
export const REGISTER_ROUTE = "/register"
export const HOME_ROUTE = "/"
export const ADMIN_ROUTE = "/admin"
export const UNAUTHORIZED_ROUTE = "/unauthorized"
